name: Deploy Browed by Olá

on:
  push:
    branches: [main]

env:
  AWS_REGION: us-east-1
  ECR_REGISTRY: 058264073944.dkr.ecr.us-east-1.amazonaws.com
  ECR_REPOSITORY: olabrows-site
  BLUE_SERVER: 54.85.135.163
  GREEN_SERVER: 3.239.170.164

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Docker image
        run: |
          docker buildx create --use
          docker buildx build --platform linux/amd64 \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:latest \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:${{ github.sha }} \
            --push .

      - name: Deploy to Blue server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.BLUE_SERVER }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 058264073944.dkr.ecr.us-east-1.amazonaws.com
            docker pull 058264073944.dkr.ecr.us-east-1.amazonaws.com/olabrows-site:latest
            docker rm -f olabrows || true
            docker run -d -p 8080:80 --name olabrows --restart always 058264073944.dkr.ecr.us-east-1.amazonaws.com/olabrows-site:latest

      - name: Deploy to Green server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.GREEN_SERVER }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 058264073944.dkr.ecr.us-east-1.amazonaws.com
            docker pull 058264073944.dkr.ecr.us-east-1.amazonaws.com/olabrows-site:latest
            docker rm -f olabrows || true
            docker run -d -p 8080:80 --name olabrows --restart always 058264073944.dkr.ecr.us-east-1.amazonaws.com/olabrows-site:latest
